name: Build and test with Java 17 and Docker

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      KNOWN_HOSTS:
        required: true
      CR_PAT:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.CR_PAT }}

jobs:

  # Builds service and runs IT tests
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Run IT tests
        run: mvn clean -B verify -Pintegration-tests

      # Get the application version set in the pom.xml
      - name: Get app version
        run: |
          echo APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

      - name: Set app version
        run: echo ${{ env.APP_VERSION }} >> app-version.txt

      - name: Print app version
        run: cat app-version.txt

      # Upload the app-version artifact to the workflow to be available for the later use: Docker tag, openapi merger job
      - name: Upload artifact - app-version
        uses: actions/upload-artifact@v2
        with:
          name: app-version
          path: app-version.txt

      # Upload the target artifact to the workflow to be available for the later use within the openapi merger job
      - name: Upload artifact - target
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: ./target
