
name: Build and test with Java 17 and Docker

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      KNOWN_HOSTS:
        required: true
      CR_PAT:
        required: true

jobs:

  # Builds service and runs IT tests
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Run IT tests
        run: mvn clean -B verify -Pintegration-tests
