name: Build and test with Java 17 and Docker

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      KNOWN_HOSTS:
        required: true
      CR_PAT:
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.CR_PAT }}

jobs:

  # Builds service and runs IT tests
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Publish Maven package to GitHub Packages
        run: mvn --batch-mode deploy

      - name: Prepare folders for artifact upload
        run: mkdir staging && cp $JAR_FILE staging

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
